### ISSUE TITLE
Code research

### ISSUE THREAD

**Issue by incogQuw** [UoSGamesGroups/first-semester-l4-5-group-12#2]
research the code needed to create a prototype level in unity 2D

**Comment by Sam0nline** [comment]
First write-up of a code assessment which defines the minimal functionality required.
Side-note: Not all the contents may be present currently but I'll keep updating as I gather more information and extend beyond minimal functions.
Link: (cannot find current one - looking for an alternative way to link the document)
[https://docs.google.com/document/d/1hw-GN3Nn0GVMEeRXiDoGoG9VeiM3nhFMU30pKhmhUnM/edit?usp=sharing](url)

Attempted to attach the .docx file but to no avail

**Comment by RiverChick** [comment]
Task has not been completed within the time given. link does not work
